import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import { trpc } from "../utils/trpc";
import Header from "../components/Header";

const TestChart = dynamic(() => import("../components/BarChart/index"), {
  ssr: false,
});

const Map = dynamic(() => import("../components/Map/index"), {
  ssr: false,
});

const Home: NextPage = () => {
  const [selectedDGUID, setSelectedDGUID] = useState("2021A000235");

  const { data: ageData } = trpc.useQuery([
    "ageData.getAgeDataByDGUID",
    { dguid: selectedDGUID },
  ]);
  const { data: geo_name } = trpc.useQuery([
    "geoNames.getGeoNameByDGUID",
    { dguid: selectedDGUID },
  ]);
  const { data: summary } = trpc.useQuery([
    "summary.getSummaryByDGUID",
    { dguid: selectedDGUID },
  ]);
  console.log("summary", summary);

  return (
    <>
      <Head>
        <title>Canada Census Visualization</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/man.png" />
      </Head>

      <Header />
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <div className="grid grid-cols-2">
          <Map setSelectedDGUID={setSelectedDGUID} />
          <div className="mx-3">
            <p className="text-xl">Currently viewing: {geo_name}</p>
            <p className="">Population: {summary?.total_population_2021}</p>
            <p className="">
              Population Growth since 2016:{" "}
              {summary?.total_population_percentage_change_2016_to_2021} %
            </p>
            <p className="">
              Population Density:{" "}
              {summary?.total_population_density_per_square_kilometre}
            </p>
            <p className="">
              Median Income: ${" "}
              {summary?.total_median_employment_income_in_2020_among_recipients}
            </p>
            <p className="">
              Average Householdsize: {summary?.total_average_household_size}
            </p>
            <p>Median Age: {summary?.total_median_age_of_the_population}</p>
          </div>
          <TestChart data={ageData} />
        </div>
        {/* <ResponsiveContainer width="100%" height="100%"> */}
        <div className="w-3/4 h-1/2"></div>
      </main>
    </>
  );
};

export default Home;
